### ISSUE TITLE
Как объявлять остановки?

### ISSUE THREAD

**Issue by UltraChannel000** [agentyzmin/metro-train-screens#23]

**Comment by SilverFire** [comment]
Описано в README.md

https://github.com/agentyzmin/metro-train-screens#serial-port-emulation

**Comment by UltraChannel000** [comment]
У меня вот.. 
![Скриншот 17-10-2019 193621](https://user-images.githubusercontent.com/49671661/67029210-8638fe00-f115-11e9-87ec-8c824d7f15a4.png)

**Comment by SilverFire** [comment]
Мануал для *NIX, на винде это делается как-то иначе, подсказать сходу не могу.
Погуглите про альтернативы socat для Windows или используйте виртуализацию/контейнеризацию

**Comment by UltraChannel000** [comment]
Ок, спасибо
