### ISSUE TITLE
Как сделать чтобы не было "Система работает в тестовом режиме"?

### ISSUE THREAD

**Issue by UltraChannel000** [agentyzmin/metro-train-screens#24]
Как сделать чтобы не было "Система работает в тестовом режиме"?

**Comment by SilverFire** [comment]
Вы представляете какую-то организацию?
Как вы планируете использовать систему?

**Comment by UltraChannel000** [comment]
Ну, можно это протестировать дома самому?

**Comment by SilverFire** [comment]
Так вроде "тестировать дома" и надпись "Система работает в тестовом режиме" никак не противоречат)

**Comment by UltraChannel000** [comment]
А всё таки можно полноценно протестировать систему?

**Comment by SilverFire** [comment]
Смотря что вы имеете ввиду пол полноценным тестированием. У вас есть голосовой информатор машиниста?

**Comment by UltraChannel000** [comment]
Нету, а можно его запустить с рекламой и всем остальным? Ну как работают мониторы в салоне метро

**Comment by SilverFire** [comment]
Система, которая воспроизводит рекламу находится за пределами этого репозитория.

> и всем остальным

Чем именно? :)

**Comment by UltraChannel000** [comment]
> Система, которая воспроизводит рекламу находится за пределами этого репозитория.

Ок
> Чем именно? :)

Ну с рекламой, может немного с другими анимациями

**Comment by UltraChannel000** [comment]
Было бы здорово увидеть у себя ту систему которую я уже много раз видел в метро)

**Comment by SilverFire** [comment]
> Ну с рекламой, может немного с другими анимациями

> Было бы здорово увидеть у себя ту систему которую я уже много раз видел в метро)

Код рекламной части закрытый и полностью воспроизвести дома систему не получится.

**Comment by UltraChannel000** [comment]
ясно, спасибо за помощь.
