### ISSUE TITLE
Выводить предупреждение при получении сообщения "Поезд едет до станции ..."

### ISSUE THREAD

**Issue by veikus** [agentyzmin/metro-train-screens#5]
Нужно корректно показывать последнюю станцию во второй версии и выводить дополнительное уведомление для пассажиров.

**Comment by SilverFire** [comment]
Механика уже известна?

**Comment by veikus** [comment]
Из того, что точно нужно реализовать в рамках этой задачи - при получении кода 0701 необходимо подменять конечную станцию во время отображения списка следующих станций и отображать сообщение "Поезд дальше не едет" по прибытию на Дарницу.

Информацию о "временной" конечной станции нужно хранить от первого получения кода до момента прибытия до конечной (то есть если код получен был на Арсенальной, то изменения в маршруте мы покажем и на Гидропарке и на Левобережке. На Дарнице будет сообщение о том, что поезд дальше не едет).

В ветке v2 уже реализовано отображение списка станций и сообщение о том, что станция конечная. Остается добавить только обработку такого варианта.

**Comment by SilverFire** [comment]
Окей, я поработаю над этим и сделаю Pull Request.

**Comment by veikus** [comment]
Спасибо, будем ждать.

**Comment by SilverFire** [comment]
Код 0701 всегда отвечает за сход с маршрута на одной и той же станции, верно?
То есть в конфиге ветки для станции, на которой поезда уходят в депо, я добавлю параметр isDepot

**Comment by veikus** [comment]
Я думаю, лучше добавить это в конфиг станции, внутрь параметра DTMF.
