### ISSUE TITLE
Отображать текущее время на дисплее

### ISSUE THREAD

**Issue by SilverFire** [agentyzmin/metro-train-screens#8]
На Facebook от многих комментаторов поступает просьба добавить отображение времени.

Насколько я понял из ответов, есть какая-то блокирующая проблема, связанная с синхронизацией времени на компьютере в поезде, верно?

**Comment by veikus** [comment]
В v2 уже реализовано отображение времени на экране со списком станций (используется системное время). Как только обновим систему - будут часы.
